-- UAP Observer PostgreSQL baseline for Supabase.
-- This schema is intentionally separate from SQLite migrations. Import a
-- reviewed JSON snapshot before enabling any public read policies.

create table if not exists sources (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    source_type text not null check (source_type in ('rss', 'api', 'web_page')),
    homepage_url text not null,
    feed_url text unique,
    country text,
    language text,
    default_category text not null,
    default_credibility integer not null check (default_credibility between 1 and 5),
    default_fact_status text not null,
    include_keywords jsonb not null default '[]'::jsonb,
    exclude_keywords jsonb not null default '[]'::jsonb,
    enabled boolean not null default true,
    etag text,
    last_modified text,
    last_fetched_at timestamptz,
    last_success_at timestamptz,
    last_error text,
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now()
);

create table if not exists news (
    id bigint generated by default as identity primary key,
    title text not null,
    original_title text not null,
    source text not null,
    source_url text not null unique,
    canonical_url text unique,
    publish_date text,
    country text,
    category text not null,
    summary text,
    credibility integer not null check (credibility between 1 and 5),
    fact_status text not null,
    key_facts jsonb not null default '[]'::jsonb,
    viewpoints jsonb not null default '[]'::jsonb,
    raw_content text,
    content_hash text unique,
    ai_model text,
    ai_processed_at timestamptz,
    processing_status text not null default 'pending',
    source_id bigint references sources(id) on delete set null,
    feed_entry_id text,
    extraction_status text not null default 'pending',
    extracted_content text,
    extracted_title text,
    extracted_author text,
    extracted_publish_date text,
    extracted_language text,
    extracted_by text,
    extraction_attempts integer not null default 0,
    extraction_started_at timestamptz,
    content_extracted_at timestamptz,
    extraction_error text,
    analysis_version text,
    analysis_attempts integer not null default 0,
    analysis_started_at timestamptz,
    analysis_error text,
    analysis_json jsonb,
    analysis_response_id text,
    analysis_confidence double precision check (analysis_confidence is null or analysis_confidence between 0 and 1),
    risk_flags jsonb not null default '[]'::jsonb,
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now(),
    unique (source_id, feed_entry_id)
);

create table if not exists organizations (
    id bigint generated by default as identity primary key,
    name text not null unique,
    country text,
    description text,
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now()
);

create table if not exists events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    date_start text,
    date_end text,
    location text,
    country text,
    description text,
    status text not null default 'unverified',
    credibility integer not null check (credibility between 1 and 5),
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now()
);

create table if not exists persons (
    id bigint generated by default as identity primary key,
    name text not null,
    country text,
    organization text,
    description text,
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now()
);

create table if not exists relationships (
    id bigint generated by default as identity primary key,
    source_type text not null check (source_type in ('news', 'event', 'person', 'organization')),
    source_id bigint not null,
    target_type text not null check (target_type in ('news', 'event', 'person', 'organization')),
    target_id bigint not null,
    relationship_type text not null,
    evidence_news_id bigint references news(id) on delete set null,
    confidence double precision check (confidence is null or confidence between 0 and 1),
    created_time timestamptz not null default now(),
    unique (source_type, source_id, target_type, target_id, relationship_type)
);

create index if not exists idx_news_publish_date on news(publish_date);
create index if not exists idx_news_processing_queue on news(processing_status, extraction_status, publish_date, id);
create index if not exists idx_events_date_start on events(date_start);
create index if not exists idx_persons_name on persons(lower(name));
create index if not exists idx_organizations_name on organizations(lower(name));
create index if not exists idx_relationships_source on relationships(source_type, source_id);
create index if not exists idx_relationships_target on relationships(target_type, target_id);

create table if not exists tags (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    tag_type text not null default 'topic',
    description text,
    parent_id bigint references tags(id) on delete set null,
    created_time timestamptz not null default now(),
    updated_time timestamptz not null default now()
);

create table if not exists tag_assignments (
    id bigint generated by default as identity primary key,
    tag_id bigint not null references tags(id) on delete cascade,
    entity_type text not null check (entity_type in ('news', 'event', 'person', 'organization')),
    entity_id bigint not null,
    source_news_id bigint references news(id) on delete set null,
    confidence double precision check (confidence is null or confidence between 0 and 1),
    method text not null default 'ai_extracted',
    status text not null default 'candidate',
    created_time timestamptz not null default now(),
    unique (tag_id, entity_type, entity_id, source_news_id)
);

create table if not exists person_relationships (
    id bigint generated by default as identity primary key,
    source_person_id bigint not null references persons(id) on delete cascade,
    target_person_id bigint not null references persons(id) on delete cascade,
    relationship_type text not null,
    confidence double precision check (confidence is null or confidence between 0 and 1),
    status text not null default 'candidate',
    method text not null default 'ai_extracted',
    first_seen_at text,
    last_seen_at text,
    created_time timestamptz not null default now(),
    unique (source_person_id, target_person_id, relationship_type),
    check (source_person_id <> target_person_id)
);

create table if not exists person_relationship_evidence (
    id bigint generated by default as identity primary key,
    person_relationship_id bigint not null references person_relationships(id) on delete cascade,
    news_id bigint not null references news(id) on delete cascade,
    evidence_text text,
    created_time timestamptz not null default now(),
    unique (person_relationship_id, news_id)
);

create index if not exists idx_tags_type on tags(tag_type);
create index if not exists idx_tag_assignments_entity on tag_assignments(entity_type, entity_id);
create index if not exists idx_person_relationships_source on person_relationships(source_person_id);
create index if not exists idx_person_relationships_target on person_relationships(target_person_id);
create index if not exists idx_person_relationship_evidence_news on person_relationship_evidence(news_id);

-- Deliberately no anon/public policies are enabled here. Add reviewed SELECT
-- policies only after deciding which fields may be publicly exposed.
